version: '3'
services:
 test1:
  build: .
  ports:
   - "8081:8080"
  environment:
   - ADM=true

 test2:
  build: .
  ports:
   - "8082:8080"

 test3:
  build: .
  ports:
   - "8083:8080"

 test4:
  build: .
  ports:
   - "8084:8080"

 test5:
  build: .
  ports:
   - "8085:8080"