version: '3'
services:
 management-center:
  image: hazelcast/management-center:latest
  ports:
   - "8080:8080"

 test1:
  build: .
  ports:
   - "8081:8080"
  environment:
   - ADM=true
  depends_on:
   - management-center

 test2:
  build: .
  ports:
   - "8082:8080"
  depends_on:
   - management-center
